import os

TOKEN_TTL_SEC = int(os.getenv("USER_TOKEN_TTL_SEC", "86400"))
PASSWORD_PEPPER = os.getenv("USER_PASSWORD_PEPPER", "")
PASSWORD_ITERATIONS = int(os.getenv("USER_PASSWORD_ITERATIONS", "200000"))

LOCKOUT_THRESHOLD = int(os.getenv("USER_LOCKOUT_THRESHOLD", "5"))
LOCKOUT_DURATION_SEC = int(os.getenv("USER_LOCKOUT_DURATION_SEC", "900"))

INVITE_TTL_DAYS = int(os.getenv("USER_INVITE_TTL_DAYS", "7"))
INVITE_MAX_ACTIVE = int(os.getenv("USER_INVITE_MAX_ACTIVE", "5"))
